CHOICES = {
    "diet_type": {
        "omnivore": "Omnivore (meat + vegetables)",
        "flexitarian": "Flexitarian (reduced meat)",
        "vegetarian": "Vegetarian (no meat, dairy OK)",
        "vegan": "Vegan (no animal products)",
        "pescatarian": "Pescatarian (fish, no meat)"
    },
    "allergies": {
        "gluten": "Gluten",
        "nuts": "Tree nuts",
        "peanuts": "Peanuts",
        "dairy": "Dairy/Lactose",
        "eggs": "Eggs",
        "soy": "Soy",
        "shellfish": "Shellfish",
        "fish": "Fish",
        "sesame": "Sesame seeds"
    },
    "cuisine_preferences": {
        "french": "French",
        "italian": "Italian",
        "asian": "Asian (Chinese, Japanese, Thai)",
        "indian": "Indian",
        "mexican": "Mexican",
        "mediterranean": "Mediterranean",
        "middle_eastern": "Middle Eastern",
        "american": "American",
        "african": "African"
    },
    "skill_level": {
        "beginner": "Beginner (simple recipes)",
        "intermediate": "Intermediate (moderate techniques)",
        "advanced": "Advanced (complex dishes)"
    },
    "sustainability_priority": {
        "co2": "Minimize CO2 emissions",
        "local": "Prioritize local/seasonal ingredients",
        "waste": "Minimize food waste",
        "balanced": "Balanced approach"
    },
    "countries": {
        "France": "France",
        "Germany": "Germany",
        "United Kingdom": "United Kingdom",
        "Spain": "Spain",
        "Italy": "Italy",
        "Portugal": "Portugal",
        "Netherlands": "Netherlands",
        "Belgium": "Belgium",
        "Switzerland": "Switzerland",
        "Sweden": "Sweden",
        "Norway": "Norway",
        "Denmark": "Denmark",
        "Finland": "Finland",
        "Austria": "Austria",
        "Poland": "Poland",
        "Greece": "Greece",
        "Czech Republic": "Czech Republic",
        "Ireland": "Ireland",
        "Romania": "Romania",
        "Morocco": "Morocco",
        "Tunisia": "Tunisia",
        "Algeria": "Algeria",
        "Egypt": "Egypt",
        "Nigeria": "Nigeria",
        "South Africa": "South Africa",
        "Kenya": "Kenya",
        "Ethiopia": "Ethiopia",
        "Senegal": "Senegal",
        "United States": "United States",
        "Canada": "Canada",
        "Mexico": "Mexico",
        "Brazil": "Brazil",
        "Argentina": "Argentina",
        "Colombia": "Colombia",
        "Peru": "Peru",
        "Chile": "Chile",
        "China": "China",
        "Japan": "Japan",
        "South Korea": "South Korea",
        "India": "India",
        "Thailand": "Thailand",
        "Vietnam": "Vietnam",
        "Indonesia": "Indonesia",
        "Philippines": "Philippines",
        "Malaysia": "Malaysia",
        "Turkey": "Turkey",
        "Israel": "Israel",
        "Lebanon": "Lebanon",
        "Australia": "Australia",
        "New Zealand": "New Zealand",
        "Russia": "Russia",
        "Ukraine": "Ukraine",
    }
}

DEFAULT_PROFILE = {
    "diet_type": "omnivore",
    "allergies": [],
    "disliked_ingredients": [],
    "cuisine_preferences": [
        "french", "italian", "mediterranean", "asian", "indian",
        "mexican", "middle_eastern", "american", "african"
    ],
    "max_cooking_time": 60,
    "skill_level": "intermediate",
    "weekly_budget": 150.0,
    "currency": "EUR",
    "household_size": 2,
    "sustainability_priority": "balanced",
    "country": "France"
}
