name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote remove space 2>/dev/null || true
          git remote add space "https://AymaneAshrk:${HF_TOKEN}@huggingface.co/spaces/AymaneAshrk/EcoMeal_Bot"
          git push --force space HEAD:main
